export const TYPE = {
  SAGA_GET_LIST_ORDER: "SAGA_GET_LIST_ORDER",
  SAGA_DELETE_ORDER: "SAGA_DELETE_ORDER",
  SAGA_SAVE_ORDER: "SAGA_SAVE_ORDER",
  SAGA_GET_ORDER: "SAGA_GET_ORDER",

  SET_LIST_ORDER: "SET_LIST_ORDER",
  SET_MESSAGE_ORDER: "SET_MESSAGE_ORDER",
  SET_ORDER: "SET_ORDER",
  SET_OPTIONS_ORDER: "SET_OPTIONS_ORDER",
};
