export const TYPE = {
  SAGA_GET_LIST_EXAM: "SAGA_GET_LIST_EXAM",
  SAGA_DELETE_EXAM: "SAGA_DELETE_EXAM",
  SAGA_SAVE_EXAM: "SAGA_SAVE_EXAM",
  SAGA_GET_EXAM: "SAGA_GET_EXAM",

  SET_LIST_EXAM: "SET_LIST_EXAM",
  SET_EXAM: "SET_EXAM",
  SET_MESSAGE_EXAM: "SET_MESSAGE_EXAM",
};
