export const TYPE = {
  SAGA_GET_LIST_CONTACT: "SAGA_GET_LIST_CONTACT",
  SAGA_DELETE_CONTACT: "SAGA_DELETE_CONTACT",
  SAGA_SAVE_CONTACT: "SAGA_SAVE_CONTACT",

  SET_LIST_CONTACT: "SET_LIST_CONTACT",
  SET_STATE_VAR_CONTACT: "SET_STATE_VAR_CONTACT",
  SET_MESSAGE_CONTACT: "SET_MESSAGE_CONTACT",
};
