export const TYPE = {
  SAGA_GET_LIST_CATEGORIES: "SAGA_GET_LIST_CATEGORIES",
  SAGE_DELETE_CATEGORY: "SAGE_DELETE_CATEGORY",
  SAGA_GET_CATEGORY: "SAGA_GET_CATEGORY",
  SAGA_SAVE_CATEGORY: "SAGA_SAVE_CATEGORY",

  SET_LIST_CATEGORY: "SET_LIST_CATEGORY",
  SET_MESSAGE_CATEGORY: "SET_MESSAGE_CATEGORY",
  SET_CATEGORY: "SET_CATEGORY",
};
