export const TYPE = {
  SAGA_GET_LIST_CATEGORIES: "SAGA_GET_LIST_CATEGORIES",
  SAGE_DELETE_CATEGORY: "SAGE_DELETE_CATEGORY",

  SET_LIST_CATEGORY: "SET_LIST_CATEGORIES",
  SET_ERROR_CATEGORY: "SET_ERROR_CATEGORY",
};