export const TYPE = {
  //SAGAS
  SAGA_GET_LIST_STORE: "SAGA_GET_LIST_STORE",
  SAGA_DELETE_STORE: "SAGA_DELETE_STORE",
  SAGA_GET_ITEM: "SAGA_GET_ITEM",
  SAGA_SAVE_ITEM: "SAGA_SAVE_ITEM",
  SAGA_GET_LIST_BRANDS: "SAGA_GET_LIST_BRANDS",
  //SET
  SET_LIST_STORE: "SET_LIST_STORE",
  SET_MESSAGE_STORE: "SET_MESSAGE_STORE",
  SET_OPTIONS: "SET_OPTIONS",
  SET_ITEM: "SET_ITEM",
  SET_LIST_BRANDS: "SET_LIST_BRANDS",
};
