export const TYPE = {
  SAGA_GET_LIST_CONFIG: "SAGA_GET_LIST_CONFIG",
  SAGA_GET_CONFIG: "SAGA_GET_CONFIG",
  SAGA_DELETE_CONFIG: "SAGA_DELETE_CONFIG",
  SAGA_SAVE_CONFIG: "SAGA_SAVE_CONFIG",

  SET_LIST_CONFIG: "SET_LIST_CONFIG",
  SET_CONFIG: "SET_CONFIG",
  SET_MESSAGE_CONFIG: "SET_MESSAGE_CONFIG",
};
