export const TYPE = {
  SAGA_GET_LIST: "SAGA_GET_LIST",
  SAGA_DELETE_ORDER: "DELETE_ORDER",
  SAGA_SAVE_ORDER: "SAGA_SAVE_ORDER",

  SET_LIST: "SET_LIST",
  SET_STATE_VAR: "SET_STATE_VAR",
  SET_ERROR: "SET_ERROR",
  SET_MESSAGE: "SET_MESSAGE",
};
