export const TYPE = {
  SAGA_GET_LIST: "SAGA_GET_LIST",
  SAGA_DELETE_ORDER: "DELETE_ORDER",
  SAGA_SAVE_ORDER: "SAGA_SAVE_ORDER",
  SAGA_GET_ORDER: "SAGA_GET_ORDER",

  SET_LIST: "SET_LIST",
  SET_MESSAGE: "SET_MESSAGE",
  SET_ORDER: "SET_ORDER",
  SET_OPTIONS: "SET_OPTIONS",
};
