export const TYPE = {
  SAGA_TRY_LOGING: "SAGA_TRY_LOGING",
  SAGA_CHECK_LOGING: "SAGA_CHECK_LOGING",
  SAGA_GET_NOTIFY: "SAGA_GET_NOTIFY",
  SAGA_READ_NOTIFYS: "SAGA_READ_NOTIFYS",
  SAGA_GET_LIST_USERS: "SAGA_GET_LIST_USERS",
  SAGA_GET_USER: "SAGA_GET_USER",
  SAGA_DELETE_USER: "SAGA_DELETE_USER",
  SAGA_SAVE_USER: "SAGA_SAVE_USER",

  SET_LOGGIN: "SET_LOGGIN",
  SET_LOGOUT: "SET_LOGOUT",
  SET_NOTIFYS: "SET_NOTIFYS",
  SET_MESSAGES: "SET_MESSAGES",
  SET_LIST_USERS: "SET_LIST_USERS",
  SET_OPTIONS_USERS: "SET_OPTIONS_USERS",
  SET_USER: "SET_USER",
};
