export const TYPE = {
    SAGA_TRY_LOGING: "SAGA_TRY_LOGING",
    SAGA_CHECK_LOGING: "SAGA_CHECK_LOGING",
    LOGING_SUCCESS: "LOGING_SUCCESS",
    LOGING_ERROR: "LOGING_ERROR",
    LOGING_DELETE: "LOGING_DELETE",

    SAGA_GET_NOTIFY: "SAGA_GET_NOTIFY",
    SAGA_READ_NOTIFYS: "SAGA_READ_NOTIFYS",
    GET_NOTIFYS: "GET_NOTIFYS",
};