export const TYPE = {
  SAGA_TRY_LOGING: "SAGA_TRY_LOGING",
  SAGA_CHECK_LOGING: "SAGA_CHECK_LOGING",
  SAGA_GET_NOTIFY: "SAGA_GET_NOTIFY",
  SAGA_READ_NOTIFYS: "SAGA_READ_NOTIFYS",

  SET_LOGGIN: "SET_LOGGIN",
  SET_LOGOUT: "SET_LOGOUT",
  SET_NOTIFYS: "SET_NOTIFYS",
  SET_MESSAGES: "SET_MESSAGES",
};
