export const TYPE = {
  SAGA_GET_LIST_SALES: "SAGA_GET_LIST_SALES",
  SAGA_DELETE_SALE: "SAGA_DELETE_SALE",
  SAGA_SAVE_SALE: "SAGA_SAVE_SALE",
  SAGA_GET_SALE: "SAGA_GET_SALE",

  SET_LIST_SALES: "SET_LIST_SALES",
  SET_SALE: "SET_SALE",
  SET_MESSAGE_SALE: "SET_MESSAGE_SALE",
};
